
UNIT_CHOICE_KELVIN = 1
UNIT_CHOICE_CELSIUS = 2
UNIT_CHOICE_FAHRENHEIT = 3

UNIT_CHOICES = (
    (UNIT_CHOICE_KELVIN, "Kelvin"),
    (UNIT_CHOICE_CELSIUS, "Celsius"),
    (UNIT_CHOICE_FAHRENHEIT, "Fahrenheit")
)
